version: '3'

services:
    nginx:
        build:
            context: ./Nginx_container
        container_name: nginx_aythae
        links:
            - app
        ports:
            - '80:80'
    mongo:
        build: ./MongoDB_container
        volumes:
            - /var/lib/mongodb:/data/db
        container_name: mongo_aythae

    app:
        build: ./App_container
        container_name: app_aythae
        links:
            - mongo
