# -*- coding: utf-8 -*-
# restaurantes/urls.py

from django.conf.urls import include, url
from rest_framework_mongoengine import routers

from . import serializers, views

# this is DRF router for REST API viewsets
router = routers.DefaultRouter()

# register REST API endpoints with DRF router
router.register(
    r'restaurants', serializers.restaurantsViewSet, r"restaurants")

# 2 Funciones que corresponden a los nombres indicados en atributo name y cuya
# definición se encuentra en el archivo views.py
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^test/$', views.test, name='test'),
    url(r'^buscar$', views.buscar, name='buscar'),
    url(r'^aniadir$', views.add, name='add'),
    url(r'^restaurante/(?P<name>.+)/imagen$', views.imagen, name='imagen'),
    url(r'^restaurante/(?P<name>.+)$', views.restaurante, name='restaurante'),
    # REST API root view (generated by DRF router)
    url(r'^api/', include(router.urls, namespace='api')),

]
